-- ==============================================================================
-- THRYVE DATABASE INITIALIZATION SCHEMA (SUPABASE)
-- Run this entire script in your new Supabase Project > SQL Editor
-- ==============================================================================

-- 1. ENABLE EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ==============================================================================
-- 2. PROFILES TABLE
-- Keeps user metadata, automatically populated when a user registers.
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    first_name TEXT,
    last_name TEXT,
    email TEXT,
    avatar_url TEXT,
    auto_generate_prototypes BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Row Level Security (RLS) for Profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own profile"
    ON public.profiles FOR SELECT
    USING (auth.uid() = id);

CREATE POLICY "Users can update their own profile"
    ON public.profiles FOR UPDATE
    USING (auth.uid() = id);

CREATE POLICY "Service role has full access to profiles"
    ON public.profiles FOR ALL
    USING (auth.jwt() ->> 'role' = 'service_role');

-- Trigger to automatically create a profile row when a new user signs up in Supabase Auth
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
    INSERT INTO public.profiles (id, email, first_name, last_name)
    VALUES (
        new.id,
        new.email,
        COALESCE(new.raw_user_meta_data->>'first_name', split_part(new.email, '@', 1)),
        COALESCE(new.raw_user_meta_data->>'last_name', '')
    )
    ON CONFLICT (id) DO UPDATE
    SET email = EXCLUDED.email,
        updated_at = timezone('utc'::text, now());
    RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ==============================================================================
-- 3. TRENDS TABLE
-- Stores AI-discovered market trends and research cards.
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.trends (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    summary TEXT,
    interpretation TEXT,
    category TEXT DEFAULT 'Banking & Fintech',
    impact TEXT DEFAULT 'Medium',
    detailed_research JSONB DEFAULT '{}'::jsonb,
    prototype_prompt TEXT,
    sources JSONB DEFAULT '[]'::jsonb,
    is_heart BOOLEAN DEFAULT FALSE,
    generation_type TEXT DEFAULT 'automatic', -- 'automatic' or 'manual'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.trends ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own trends or public trends"
    ON public.trends FOR SELECT
    USING (auth.uid() = user_id OR user_id IS NULL);

CREATE POLICY "Users can insert their own trends"
    ON public.trends FOR INSERT
    WITH CHECK (auth.uid() = user_id OR auth.uid() IS NOT NULL);

CREATE POLICY "Users can update their own trends"
    ON public.trends FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own trends"
    ON public.trends FOR DELETE
    USING (auth.uid() = user_id);

-- ==============================================================================
-- 4. PROTOTYPES TABLE
-- Stores interactive UI prototypes generated by Gemini.
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.prototypes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    trend_id UUID REFERENCES public.trends(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    description TEXT,
    category TEXT DEFAULT 'Fintech',
    priority TEXT DEFAULT 'Medium',
    prompt TEXT NOT NULL,
    status TEXT DEFAULT 'Generating', -- 'Generating', 'Ready', 'Failed'
    error_message TEXT,
    prototype_code TEXT, -- Full self-contained interactive HTML/JS code generated by Gemini
    v0_project_id TEXT, -- Maintained for backwards compatibility
    v0_url TEXT, -- Preview URL pointing to /api/prototypes/preview/[id]
    generation_started_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    generation_completed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.prototypes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own prototypes"
    ON public.prototypes FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own prototypes"
    ON public.prototypes FOR INSERT
    WITH CHECK (auth.uid() = user_id OR auth.uid() IS NOT NULL);

CREATE POLICY "Users can update their own prototypes"
    ON public.prototypes FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own prototypes"
    ON public.prototypes FOR DELETE
    USING (auth.uid() = user_id);

-- ==============================================================================
-- 5. UTILITIES TABLE & VERSIONS
-- Stores uploaded CSV datasets and AI-generated interactive dashboards.
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.utilities (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    file_name TEXT NOT NULL,
    file_link TEXT NOT NULL,
    file_size BIGINT DEFAULT 0,
    charts_count INTEGER DEFAULT 0,
    generated_code TEXT, -- Complete self-contained HTML/Chart dashboard code
    dashboard_url TEXT, -- URL pointing to /api/utilities/dashboard/[id]
    sandbox_id TEXT,
    cache_key TEXT,
    status TEXT DEFAULT 'ready', -- 'uploaded', 'generating-dashboard', 'ready', 'error'
    error_message TEXT,
    dashboard_data JSONB DEFAULT '{}'::jsonb, -- Structured metrics and charts data
    dashboard_expires_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.utilities ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own utilities"
    ON public.utilities FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own utilities"
    ON public.utilities FOR INSERT
    WITH CHECK (auth.uid() = user_id OR auth.uid() IS NOT NULL);

CREATE POLICY "Users can update their own utilities"
    ON public.utilities FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own utilities"
    ON public.utilities FOR DELETE
    USING (auth.uid() = user_id);

CREATE TABLE IF NOT EXISTS public.utility_versions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    utility_id UUID REFERENCES public.utilities(id) ON DELETE CASCADE,
    version_number INTEGER NOT NULL,
    file_name TEXT NOT NULL,
    file_link TEXT NOT NULL,
    file_size BIGINT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.utility_versions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their utility versions"
    ON public.utility_versions FOR SELECT
    USING (EXISTS (
        SELECT 1 FROM public.utilities u
        WHERE u.id = utility_versions.utility_id AND u.user_id = auth.uid()
    ));

CREATE POLICY "Users can insert utility versions"
    ON public.utility_versions FOR INSERT
    WITH CHECK (EXISTS (
        SELECT 1 FROM public.utilities u
        WHERE u.id = utility_versions.utility_id AND u.user_id = auth.uid()
    ));

-- ==============================================================================
-- 6. NEWS EVENTS TABLE
-- Stores grounded news articles fetched with Gemini Search Grounding.
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.news_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    summary TEXT,
    source TEXT,
    url TEXT,
    image_url TEXT,
    published_at TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.news_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their news events"
    ON public.news_events FOR SELECT
    USING (auth.uid() = user_id OR user_id IS NULL);

CREATE POLICY "Users can insert news events"
    ON public.news_events FOR INSERT
    WITH CHECK (auth.uid() = user_id OR auth.uid() IS NOT NULL);

CREATE POLICY "Users can delete their news events"
    ON public.news_events FOR DELETE
    USING (auth.uid() = user_id);

-- ==============================================================================
-- 7. TEAMS & COLLABORATION TABLES
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.teams (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    description TEXT,
    created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Team members can view teams" ON public.teams FOR SELECT USING (true);
CREATE POLICY "Authenticated users can create teams" ON public.teams FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);

CREATE TABLE IF NOT EXISTS public.team_members (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    team_id UUID REFERENCES public.teams(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    role TEXT DEFAULT 'member',
    joined_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(team_id, user_id)
);

ALTER TABLE public.team_members ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Team members can view memberships" ON public.team_members FOR SELECT USING (true);
CREATE POLICY "Users can join teams" ON public.team_members FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE TABLE IF NOT EXISTS public.team_announcements (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    team_id UUID REFERENCES public.teams(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.team_announcements ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Team members can view announcements" ON public.team_announcements FOR SELECT USING (true);
CREATE POLICY "Team members can insert announcements" ON public.team_announcements FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);

CREATE TABLE IF NOT EXISTS public.team_projects (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    team_id UUID REFERENCES public.teams(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    status TEXT DEFAULT 'active',
    created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.team_projects ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Team members can view team projects" ON public.team_projects FOR SELECT USING (true);
CREATE POLICY "Team members can insert team projects" ON public.team_projects FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);

CREATE TABLE IF NOT EXISTS public.team_chat_messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    team_id UUID REFERENCES public.teams(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.team_chat_messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Team members can view chat messages" ON public.team_chat_messages FOR SELECT USING (true);
CREATE POLICY "Team members can insert chat messages" ON public.team_chat_messages FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);

-- ==============================================================================
-- 8. STORAGE BUCKETS SETUP
-- Creates the required storage buckets for file uploads.
-- ==============================================================================
INSERT INTO storage.buckets (id, name, public)
VALUES ('utilities-files', 'utilities-files', true)
ON CONFLICT (id) DO UPDATE SET public = true;

INSERT INTO storage.buckets (id, name, public)
VALUES ('prototypes', 'prototypes', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Storage Policies
CREATE POLICY "Public Access for utilities-files"
ON storage.objects FOR SELECT
USING (bucket_id = 'utilities-files');

CREATE POLICY "Authenticated users can upload to utilities-files"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'utilities-files' AND auth.uid() IS NOT NULL);

CREATE POLICY "Public Access for prototypes"
ON storage.objects FOR SELECT
USING (bucket_id = 'prototypes');

CREATE POLICY "Authenticated users can upload to prototypes"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'prototypes' AND auth.uid() IS NOT NULL);
