import { type NextRequest, NextResponse } from "next/server"
import { createClient as createSupabaseClient } from "@supabase/supabase-js"
import { generateInteractivePrototypeUI } from "@/lib/gemini"

export const dynamic = "force-dynamic"
export const revalidate = 0
export const maxDuration = 60

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
const supabaseAdmin = createSupabaseClient(supabaseUrl, serviceRoleKey)

export async function POST(request: NextRequest) {
  try {
    console.log("[PROTOTYPES-API] Prototype Generation Request")
    const body = await request.json()
    let { prompt, title, description, category = "Fintech", priority = "Medium", trendId, userId } = body

    if (!prompt) {
      return NextResponse.json({ error: "Prompt is required" }, { status: 400 })
    }

    // Sanitize prompt to eliminate any BPI mentions
    const cleanPrompt = prompt
      .replace(/\bBPI's\b/gi, "Thryve's")
      .replace(/\bBPI\b/gi, "Thryve")
      .replace(/\bBank of the Philippine Islands\b/gi, "Thryve")

    // Extract user from authorization header if not provided in payload
    if (!userId) {
      try {
        const authHeader = request.headers.get("authorization")
        if (authHeader && authHeader.startsWith("Bearer ")) {
          const token = authHeader.replace("Bearer ", "")
          const { data: { user } } = await supabaseAdmin.auth.getUser(token)
          if (user) userId = user.id
        }
      } catch {
        // Continue with null userId for demo/guest
      }
    }

    // Check for existing prototype with same title/user
    let existingQuery = supabaseAdmin
      .from("prototypes")
      .select("id, status")
      .eq("title", title || "Generated Prototype")

    if (userId) {
      existingQuery = existingQuery.eq("user_id", userId)
    } else {
      existingQuery = existingQuery.is("user_id", null)
    }

    const { data: existingPrototype } = await existingQuery
      .order("created_at", { ascending: false })
      .limit(1)
      .maybeSingle()

    let prototypeId: string
    let isUpdate = false

    if (existingPrototype) {
      prototypeId = existingPrototype.id
      isUpdate = true
      await supabaseAdmin
        .from("prototypes")
        .update({
          prompt: cleanPrompt,
          status: "Generating",
          generation_started_at: new Date().toISOString(),
        })
        .eq("id", prototypeId)
    } else {
      const { data: prototype, error: insertError } = await supabaseAdmin
        .from("prototypes")
        .insert({
          user_id: userId || null,
          trend_id: trendId || null,
          title: title || "Generated Prototype",
          description: description || "Interactive prototype generated by Gemini",
          category,
          priority,
          prompt: cleanPrompt,
          status: "Generating",
          generation_started_at: new Date().toISOString(),
        })
        .select()
        .single()

      if (insertError || !prototype) {
        console.error("[PROTOTYPES-API] Database insert error:", insertError)
        return NextResponse.json({ error: "Failed to create prototype record" }, { status: 500 })
      }

      prototypeId = prototype.id
    }

    // Fire generation in the background
    generatePrototypeAsync({
      prototypeId,
      prompt: cleanPrompt,
      title: title || "Generated Prototype",
      description,
      category,
      userId,
    })

    return NextResponse.json({
      success: true,
      prototypeId,
      status: "generating",
      message: isUpdate ? "Prototype update started" : "Prototype generation started",
      isUpdate,
    })
  } catch (error: any) {
    console.error("[PROTOTYPES-API] Request failed:", error)
    return NextResponse.json({ error: error?.message || "Internal server error" }, { status: 500 })
  }
}

async function generatePrototypeAsync(params: {
  prototypeId: string
  prompt: string
  title: string
  description?: string
  category?: string
  userId?: string | null
}) {
  const { prototypeId, prompt, title, description, category } = params

  try {
    console.log(`[PROTOTYPES-GEMINI] Generating interactive prototype UI for ${title} (${prototypeId})...`)
    const html = await generateInteractivePrototypeUI({
      prompt,
      title,
      description,
      category,
    })

    const previewUrl = `/api/prototypes/preview/${prototypeId}`

    console.log(`[PROTOTYPES-GEMINI] Prototype generated successfully! Length: ${html.length} chars`)
    await supabaseAdmin
      .from("prototypes")
      .update({
        prototype_code: html,
        v0_url: previewUrl,
        v0_project_id: prototypeId,
        status: "Ready",
        error_message: null,
        generation_completed_at: new Date().toISOString(),
      })
      .eq("id", prototypeId)

    console.log("[PROTOTYPES-GEMINI] Database updated with ready status and preview URL")
  } catch (error: any) {
    console.error("[PROTOTYPES-GEMINI] Generation failed:", error)
    await supabaseAdmin
      .from("prototypes")
      .update({
        status: "Failed",
        error_message: error instanceof Error ? error.message : "Failed to generate prototype UI",
        generation_completed_at: new Date().toISOString(),
      })
      .eq("id", prototypeId)
  }
}

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    let userId = searchParams.get("userId")

    if (!userId) {
      try {
        const authHeader = request.headers.get("authorization")
        if (authHeader && authHeader.startsWith("Bearer ")) {
          const token = authHeader.replace("Bearer ", "")
          const { data: { user } } = await supabaseAdmin.auth.getUser(token)
          if (user) userId = user.id
        }
      } catch {
        // Continue with null userId
      }
    }

    let query = supabaseAdmin
      .from("prototypes")
      .select(`
        *,
        trends (
          title,
          category,
          impact
        )
      `)
      .order("created_at", { ascending: false })

    if (userId) {
      query = query.or(`user_id.eq.${userId},user_id.is.null`)
    }

    const { data: prototypes, error } = await query

    if (error) {
      console.error("[PROTOTYPES-API] Query error:", error)
      return NextResponse.json({ error: error.message }, { status: 500 })
    }

    return NextResponse.json({ success: true, prototypes: prototypes || [] })
  } catch (error: any) {
    console.error("[PROTOTYPES-API] GET error:", error)
    return NextResponse.json({ error: error?.message || "Internal server error" }, { status: 500 })
  }
}
